### PR TITLE
Fixed the typo on the installation command

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**

### CODE REVIEW

**Comment by kimroen** [comment]
I actually think maybe the name of the addon on npm (and in the `package.json`) might be the actual typo, but this is actually the name of the addon on there indeed.

**Comment by sivakumar-kailasam** [comment]
@kimroen except for this repo's name, the published addon and the package.json both uses this term.

https://www.npmjs.com/package/ember-browsery-stats
https://github.com/stefanpenner/ember-browser-stats/blob/master/package.json#L2

**Comment by kimroen** [comment]
Yes, but [the initializer](https://github.com/stefanpenner/ember-browser-stats/blob/b322d4735ec9f5eecaf85ccec46b1390d9f920e1/app/initializers/ember-browser-stats.js#L5) uses `ember-browser-stats`. Both the published addon name and the name in `package.json` is created by the same command (`npm init`), so it's more likely that this one is the typo. 

Either way though, the name is the name, so @stefanpenner will just have to pick one - most likely `ember-browsery-stats`, as about 80 people have installed it already :)

**Comment by sivakumar-kailasam** [comment]
I'm happy as long as all the names are in sync :smiley:

**Comment by stefanpenner** [comment]
haha this is totally a typo, the question is should it remain?

**Comment by kimroen** [comment]
And then you have a third one `ember-memory-stats` in the readme, so who knows at this point ^^

Going with `ember-browsery-stats` is easiest, but if you're ever going to rename, then this is probably the time to do it. Can you redirect an npm-package?

**Comment by stefanpenner** [comment]
oh man, this is a funny bug.

`ember-browsery-stats` it is!

**Comment by stefanpenner** [comment]
@sivakumar-kailasam thanks for pointing all this out, i feel silly.

**Comment by kimroen** [comment]
This is the best.

**Comment by sivakumar-kailasam** [comment]
@stefanpenner happens :smile:

**Pull request closed without merging**
